package govpx

import "testing"

func TestVP9EncoderPublicControlSurfaceHasParityMapping(t *testing.T) {
	methods := exportedMethodSet(t, (*VP9Encoder)(nil))
	want := map[string]controlParityMapping{
		"Close":                          {kind: "lifecycle"},
		"Codec":                          {kind: "metadata-api"},
		"CollectFirstPassStats":          {kind: "libvpx-first-pass-oracle"},
		"Encode":                         {kind: "allocating-encode-api"},
		"EncodeIntraOnlyFrame":           {kind: "allocating-frame-flag-api"},
		"EncodeIntraOnlyFrameInto":       {kind: "frame-flag-api"},
		"EncodeInto":                     {kind: "encode-api"},
		"EncodeIntoWithFlags":            {kind: "frame-flag-api"},
		"EncodeIntoWithFlagsResult":      {kind: "frame-flag-api"},
		"EncodeIntoWithResult":           {kind: "encode-api"},
		"EncodeShowExistingFrame":        {kind: "allocating-vp9-show-existing-api"},
		"EncodeShowExistingFrameInto":    {kind: "vp9-show-existing-api"},
		"EncodeWithFlags":                {kind: "allocating-frame-flag-api"},
		"FlushInto":                      {kind: "vp9-lookahead-api"},
		"FlushIntoWithResult":            {kind: "vp9-lookahead-api"},
		"ForceKeyFrame":                  {kind: "frame-flag-api"},
		"LastLoopFilterLevel":            {kind: "libvpx-control"},
		"IsKeyFrameNext":                 {kind: "metadata-api"},
		"LastQuantizer":                  {kind: "metadata-api"},
		"CopyReferenceFrame":             {kind: "libvpx-control", helperTokens: []string{"copyref:"}},
		"SetAdaptiveKeyFrames":           {kind: "vp9-scene-cut-control"},
		"SetAQMode":                      {kind: "libvpx-control", helperTokens: []string{"aq:"}},
		"SetARNR":                        {kind: "libvpx-control", helperTokens: []string{"arnrmax:", "arnrstrength:", "arnrtype:"}},
		"SetActiveMap":                   {kind: "libvpx-control", helperTokens: []string{"active:"}},
		"SetAutoAltRef":                  {kind: "libvpx-control", helperTokens: []string{"autoaltref:"}},
		"SetBitrateKbps":                 {kind: "libvpx-config", helperTokens: []string{"bitrate:"}},
		"SetCPUUsed":                     {kind: "libvpx-control", helperTokens: []string{"cpu:"}},
		"SetCQLevel":                     {kind: "libvpx-control", helperTokens: []string{"cq:"}},
		"SetColorRange":                  {kind: "libvpx-control", helperTokens: []string{"colorrange:"}},
		"SetColorSpace":                  {kind: "libvpx-control", helperTokens: []string{"colorspace:"}},
		"SetDeadline":                    {kind: "encode-deadline", helperTokens: []string{"deadline:"}},
		"SetAltRefAQ":                    {kind: "libvpx-control", helperTokens: []string{"altrefaq:"}},
		"SetDeltaQUV":                    {kind: "libvpx-control", helperTokens: []string{"deltaquv:"}},
		"SetDisableLoopfilter":           {kind: "libvpx-control", helperTokens: []string{"disableloopfilter:"}},
		"SetDisableOvershootMaxQCBR":     {kind: "libvpx-control", helperTokens: []string{"disovershoot:"}},
		"SetEnableTPL":                   {kind: "libvpx-vp9-tpl-control"},
		"SetEnableKeyFrameFiltering":     {kind: "libvpx-control", helperTokens: []string{"--enable-keyframe-filtering"}},
		"GetActiveMap":                   {kind: "libvpx-control", helperTokens: []string{"active:"}},
		"TPLFrameDelta":                  {kind: "libvpx-vp9-tpl-control"},
		"SetFrameDropAllowed":            {kind: "libvpx-config", helperTokens: []string{"drop:"}},
		"SetFramePeriodicBoost":          {kind: "libvpx-control", helperTokens: []string{"periodicboost:"}},
		"SetFrameParallelDecoding":       {kind: "libvpx-control", helperTokens: []string{"frame-parallel:"}},
		"SetFrameParallelEncoderThreads": {kind: "vp9-frame-parallel-encoder-threads"},
		"SetGFCBRBoostPct":               {kind: "libvpx-control", helperTokens: []string{"gfboost:"}},
		"SetKeyFrameInterval":            {kind: "libvpx-config", helperTokens: []string{"kfmax:"}},
		"SetKeyFrameIntervalRange":       {kind: "libvpx-config", helperTokens: []string{"kfmin:", "kfmax:"}},
		"SetMaxGFInterval":               {kind: "libvpx-control", helperTokens: []string{"maxgf:"}},
		"SetMaxInterBitratePct":          {kind: "libvpx-control", helperTokens: []string{"maxinter:"}},
		"SetMaxIntraBitratePct":          {kind: "libvpx-control", helperTokens: []string{"maxintra:"}},
		"SetMinGFInterval":               {kind: "libvpx-control", helperTokens: []string{"mingf:"}},
		"SetNextFrameQIndex":             {kind: "libvpx-control", helperTokens: []string{"qonepass:"}},
		"SetPostEncodeDrop":              {kind: "libvpx-control", helperTokens: []string{"postdrop:"}},
		"SetLossless":                    {kind: "libvpx-control", helperTokens: []string{"lossless:"}},
		"SetNoiseSensitivity":            {kind: "libvpx-control", helperTokens: []string{"noise:"}},
		"SetRateControl":                 {kind: "libvpx-config", helperTokens: []string{"endusage:", "bitrate:", "minq:", "maxq:", "bufsz:", "bufinit:", "bufopt:", "drop:", "cq:"}},
		"SetRateControlBuffer":           {kind: "libvpx-config", helperTokens: []string{"bufsz:", "bufinit:", "bufopt:"}},
		"SetRealtimeTarget":              {kind: "libvpx-config", helperTokens: []string{"resize:", "bitrate:", "fps:", "minq:", "maxq:", "drop:"}},
		"SetRowMT":                       {kind: "libvpx-control", helperTokens: []string{"rowmt:"}},
		"SetRTCExternalRateControl":      {kind: "libvpx-control", helperTokens: []string{"rtc:"}},
		"SetReferenceFrame":              {kind: "libvpx-control", helperTokens: []string{"setref:"}},
		"SetRenderSize":                  {kind: "libvpx-control", helperTokens: []string{"rendersize:"}},
		"SetROIMap":                      {kind: "libvpx-control", helperTokens: []string{"roi:", "roicustom:"}},
		"SetScreenContentMode":           {kind: "libvpx-control", helperTokens: []string{"screen:"}},
		"SetSharpness":                   {kind: "libvpx-control", helperTokens: []string{"sharpness:"}},
		"SetSpatialLayerID":              {kind: "libvpx-vp9-svc-layer-control"},
		"SetSpatialScalability":          {kind: "libvpx-vp9-svc-control"},
		"SetStaticThreshold":             {kind: "libvpx-control", helperTokens: []string{"static:"}},
		"SetTemporalLayerID":             {kind: "libvpx-control", helperTokens: []string{"tlid:"}},
		"SetTargetLevel":                 {kind: "libvpx-control", helperTokens: []string{"targetlevel:"}},
		"SetTemporalScalability":         {kind: "libvpx-config", helperTokens: []string{"tslayers:", "tsperiodicity:", "tsbitrates:", "tsdecimators:", "tsids:"}},
		"SetTuning":                      {kind: "libvpx-control", helperTokens: []string{"tune:"}},
		"SetTwoPassStats":                {kind: "libvpx-two-pass"},
	}
	assertPublicMethodMappings(t, "VP9Encoder", methods, want)
	assertVP9FrameFlagsDriverTokens(t, want)
}

func TestVP9EncoderOptionsHaveParityMapping(t *testing.T) {
	fields := exportedFieldSet(t, VP9EncoderOptions{})
	want := map[string]controlParityMapping{
		"AdaptiveKeyFrames":   {kind: "vp9-scene-cut-control"},
		"AltRefAQ":            {kind: "libvpx-control", helperTokens: []string{"altrefaq:", "--alt-ref-aq"}},
		"AQMode":              {kind: "libvpx-vp9-aq-mode-scoreboard"},
		"ARNRMaxFrames":       {kind: "libvpx-control", helperTokens: []string{"arnrmax:", "--arnr-maxframes"}},
		"ARNRStrength":        {kind: "libvpx-control", helperTokens: []string{"arnrstrength:", "--arnr-strength"}},
		"ARNRType":            {kind: "libvpx-control", helperTokens: []string{"arnrtype:", "--arnr-type"}},
		"AutoAltRef":          {kind: "libvpx-control", helperTokens: []string{"autoaltref:", "--auto-alt-ref"}},
		"BufferInitialSizeMs": {kind: "libvpx-config", helperTokens: []string{"bufinit:", "--buf-initial-sz"}},
		"BufferOptimalSizeMs": {kind: "libvpx-config", helperTokens: []string{"bufopt:", "--buf-optimal-sz"}},
		"BufferSizeMs":        {kind: "libvpx-config", helperTokens: []string{"bufsz:", "--buf-sz"}},
		"ColorRange":          {kind: "libvpx-control", helperTokens: []string{"colorrange:", "--color-range"}},
		"ColorSpace":          {kind: "libvpx-control", helperTokens: []string{"colorspace:", "--color-space"}},
		"CpuUsed":             {kind: "libvpx-control", helperTokens: []string{"cpu:", "--cpu-used"}},
		"CQLevel":             {kind: "libvpx-control", helperTokens: []string{"cq:", "--cq-level"}},
		"Deadline":            {kind: "encode-deadline", helperTokens: []string{"deadline:", "--deadline"}},
		"DeltaQUV":            {kind: "libvpx-control", helperTokens: []string{"deltaquv:"}},
		"DisableLoopfilter":   {kind: "libvpx-control", helperTokens: []string{"disableloopfilter:", "--disable-loopfilter"}},
		"DisableOvershootMaxQCBR": {
			kind:         "libvpx-control",
			helperTokens: []string{"disovershoot:", "--disable-overshoot-maxq-cbr"},
		},
		"DropFrameAllowed":        {kind: "libvpx-config", helperTokens: []string{"drop:"}},
		"DropFrameWaterMark":      {kind: "libvpx-config", helperTokens: []string{"drop:"}},
		"EnableTPL":               {kind: "libvpx-vp9-tpl-control"},
		"EnableKeyFrameFiltering": {kind: "libvpx-control", helperTokens: []string{"--enable-keyframe-filtering"}},
		"FramePeriodicBoost":      {kind: "libvpx-control", helperTokens: []string{"periodicboost:", "--frame-boost"}},
		"ErrorResilient":          {kind: "libvpx-config", helperTokens: []string{"error:", "--error-resilient"}},
		"FPS":                     {kind: "libvpx-config", helperTokens: []string{"fps:"}},
		"FrameParallelDecoding": {
			kind:         "libvpx-control",
			helperTokens: []string{"frame-parallel:", "--frame-parallel"},
		},
		"FrameParallelDecodingSet":    {kind: "local-default-selector"},
		"FrameParallelEncoderThreads": {kind: "vp9-frame-parallel-encoder-threads"},
		"Height":                      {kind: "libvpx-config-dimensions"},
		"Log2TileRows":                {kind: "libvpx-config", helperTokens: []string{"--tile-rows"}},
		"LookaheadFrames":             {kind: "vp9-lookahead-api"},
		"Lossless":                    {kind: "libvpx-control", helperTokens: []string{"lossless:", "--lossless"}},
		"GFCBRBoostPct":               {kind: "libvpx-control", helperTokens: []string{"gfboost:", "--gf-cbr-boost"}},
		"MaxBitrateKbps":              {kind: "libvpx-config", helperTokens: []string{"--max-bitrate"}},
		"MaxGFInterval":               {kind: "libvpx-control", helperTokens: []string{"maxgf:", "--max-gf-interval"}},
		"MaxInterBitratePct":          {kind: "libvpx-control", helperTokens: []string{"maxinter:"}},
		"MaxIntraBitratePct":          {kind: "libvpx-control", helperTokens: []string{"maxintra:", "--max-intra-rate"}},
		"RTCExternalRateControl":      {kind: "libvpx-control", helperTokens: []string{"rtc:"}},
		"RenderHeight":                {kind: "libvpx-control", helperTokens: []string{"rendersize:", "--render-height"}},
		"RenderWidth":                 {kind: "libvpx-control", helperTokens: []string{"rendersize:", "--render-width"}},
		"TargetLevel":                 {kind: "libvpx-control", helperTokens: []string{"targetlevel:", "--target-level"}},
		"MaxKeyframeInterval":         {kind: "libvpx-config", helperTokens: []string{"kfmax:", "--kf-max-dist"}},
		"MinBitrateKbps":              {kind: "libvpx-config", helperTokens: []string{"--min-bitrate"}},
		"MinGFInterval":               {kind: "libvpx-control", helperTokens: []string{"mingf:", "--min-gf-interval"}},
		"MinKeyframeInterval":         {kind: "libvpx-config", helperTokens: []string{"kfmin:", "--kf-min-dist"}},
		"NextFrameQIndex":             {kind: "libvpx-control", helperTokens: []string{"qonepass:"}},
		"NextFrameQIndexSet":          {kind: "local-default-selector"},
		"PostEncodeDrop":              {kind: "libvpx-control", helperTokens: []string{"postdrop:", "--postencode-drop"}},
		"MaxQuantizer":                {kind: "libvpx-config", helperTokens: []string{"maxq:", "--max-q"}},
		"MinQuantizer":                {kind: "libvpx-config", helperTokens: []string{"minq:", "--min-q"}},
		"OvershootPct":                {kind: "libvpx-config", helperTokens: []string{"overshoot:", "--overshoot-pct"}},
		"UndershootPct":               {kind: "libvpx-config", helperTokens: []string{"undershoot:", "--undershoot-pct"}},
		"NoiseSensitivity":            {kind: "libvpx-control", helperTokens: []string{"noise:", "--noise-sensitivity"}},
		"Quantizer":                   {kind: "local-low-level-qindex"},
		"RateControlMode":             {kind: "libvpx-config", helperTokens: []string{"endusage:", "--end-usage"}},
		"RateControlModeSet":          {kind: "local-default-selector"},
		"RowMT":                       {kind: "libvpx-control", helperTokens: []string{"rowmt:", "--row-mt"}},
		"Segmentation":                {kind: "vp9-segmentation-header-api"},
		"ScreenContentMode":           {kind: "libvpx-control", helperTokens: []string{"screen:", "--tune-content"}},
		"Sharpness":                   {kind: "libvpx-control", helperTokens: []string{"sharpness:", "--sharpness"}},
		"SpatialScalability":          {kind: "libvpx-vp9-svc-control"},
		"StaticThreshold":             {kind: "libvpx-control", helperTokens: []string{"static:", "--static-thresh"}},
		"TargetBitrateKbps":           {kind: "libvpx-config", helperTokens: []string{"bitrate:", "--target-bitrate"}},
		"TemporalScalability":         {kind: "libvpx-config", helperTokens: []string{"tslayers:", "tsperiodicity:", "tsbitrates:", "tsdecimators:", "tsids:"}},
		"Threads":                     {kind: "libvpx-config", helperTokens: []string{"--tile-columns"}},
		"TimebaseDen":                 {kind: "libvpx-config-timebase"},
		"TimebaseNum":                 {kind: "libvpx-config-timebase"},
		"Tuning":                      {kind: "libvpx-control", helperTokens: []string{"tune:", "--tune"}},
		"TwoPassMaxPct":               {kind: "libvpx-two-pass"},
		"TwoPassMinPct":               {kind: "libvpx-two-pass"},
		"TwoPassStats":                {kind: "libvpx-two-pass"},
		"TwoPassVBRBiasPct":           {kind: "libvpx-two-pass"},
		"VBRCorpusComplexity":         {kind: "libvpx-two-pass"},
		"Width":                       {kind: "libvpx-config-dimensions"},
	}
	assertOptionFieldMappings(t, "VP9EncoderOptions", fields, want)
	assertVP9FrameFlagsDriverTokens(t, want)
}

func TestVP9DecoderPublicControlSurfaceHasParityMapping(t *testing.T) {
	methods := exportedMethodSet(t, (*VP9Decoder)(nil))
	want := map[string]controlParityMapping{
		"ClearSVCSpatialLayer":     {kind: "libvpx-decoder-control"},
		"Close":                    {kind: "lifecycle"},
		"Codec":                    {kind: "metadata-api"},
		"CopyCurrentFrame":         {kind: "libvpx-decoder-control"},
		"CopyReferenceFrame":       {kind: "libvpx-decoder-control", helperTokens: []string{"copyref:"}},
		"Decode":                   {kind: "libvpx-decode-oracle"},
		"DecodeInto":               {kind: "libvpx-decode-oracle"},
		"DecodeIntoWithPTS":        {kind: "local-pts-wrapper"},
		"DecodeWithPTS":            {kind: "local-pts-wrapper"},
		"LastBitDepth":             {kind: "metadata-api"},
		"LastDisplaySize":          {kind: "metadata-api"},
		"LastFrameCorrupted":       {kind: "metadata-api"},
		"LastFrameInfo":            {kind: "metadata-api"},
		"LastFrameSize":            {kind: "metadata-api"},
		"LastReferenceUpdates":     {kind: "metadata-api"},
		"NextFrame":                {kind: "decode-api"},
		"Reset":                    {kind: "lifecycle"},
		"SetByteAlignment":         {kind: "libvpx-decoder-control"},
		"SetDecodeTileCol":         {kind: "libvpx-decoder-control"},
		"SetDecodeTileRow":         {kind: "libvpx-decoder-control"},
		"SetFrameBufferFunctions":  {kind: "libvpx-decoder-control"},
		"SetInvertTileDecodeOrder": {kind: "libvpx-decoder-control"},
		"SetLoopFilterOpt":         {kind: "libvpx-decoder-control"},
		"SetReferenceFrame":        {kind: "libvpx-decoder-control", helperTokens: []string{"setref:"}},
		"SetRowMT":                 {kind: "libvpx-decoder-control"},
		"SetSkipLoopFilter":        {kind: "libvpx-decoder-control"},
		"SetSVCSpatialLayer":       {kind: "libvpx-decoder-control"},
	}
	assertPublicMethodMappings(t, "VP9Decoder", methods, want)
	assertDecoderControlTokens(t, want)
}

func TestVP9DecoderOptionsHaveParityMapping(t *testing.T) {
	fields := exportedFieldSet(t, VP9DecoderOptions{})
	want := map[string]controlParityMapping{
		"ByteAlignment":          {kind: "libvpx-decoder-control"},
		"DecodeTileCol":          {kind: "libvpx-decoder-control"},
		"DecodeTileColSet":       {kind: "libvpx-decoder-control"},
		"DecodeTileRow":          {kind: "libvpx-decoder-control"},
		"DecodeTileRowSet":       {kind: "libvpx-decoder-control"},
		"DecoderLoopFilterOpt":   {kind: "libvpx-decoder-control"},
		"DecoderRowMT":           {kind: "libvpx-decoder-control"},
		"Decryptor":              {kind: "libvpx-decoder-control"},
		"DecryptorState":         {kind: "libvpx-decoder-control"},
		"ErrorConcealment":       {kind: "libvpx-decode-oracle"},
		"GetFrameBuffer":         {kind: "libvpx-decoder-control"},
		"InvertTileDecodeOrder":  {kind: "libvpx-decoder-control"},
		"MaxHeight":              {kind: "local-validation"},
		"MaxWidth":               {kind: "local-validation"},
		"PostProcessFlags":       {kind: "libvpx-decode-oracle"},
		"PostProcessNoiseLevel":  {kind: "libvpx-decode-oracle"},
		"RejectResolutionChange": {kind: "local-validation"},
		"ReleaseFrameBuffer":     {kind: "libvpx-decoder-control"},
		"SkipLoopFilter":         {kind: "libvpx-decoder-control"},
		"SVCSpatialLayer":        {kind: "libvpx-decoder-control"},
		"SVCSpatialLayerSet":     {kind: "libvpx-decoder-control"},
		"Threads":                {kind: "libvpx-decode-oracle"},
	}
	assertOptionFieldMappings(t, "VP9DecoderOptions", fields, want)
}

func TestVP9SpatialSVCEncoderPublicControlSurfaceHasParityMapping(t *testing.T) {
	methods := exportedMethodSet(t, (*VP9SpatialSVCEncoder)(nil))
	want := map[string]controlParityMapping{
		"Close":                {kind: "lifecycle"},
		"EncodeInto":           {kind: "vp9-spatial-svc-superframe-api"},
		"EncodeIntoWithResult": {kind: "vp9-spatial-svc-superframe-api"},
		"ForceKeyFrame":        {kind: "frame-flag-api"},
		"GetLayerActiveMap":    {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"active:"}},
		"IsKeyFrameNext":       {kind: "metadata-api"},
		"LastLayerQuantizers":  {kind: "libvpx-vp9-svc-control"},
		"LayerEncoder":         {kind: "vp9-spatial-svc-layer-control"},
		"CopyLayerReferenceFrame": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"copyref:"},
		},
		"SetLayerAdaptiveKeyFrames": {kind: "vp9-spatial-svc-layer-control"},
		"SetLayerAltRefAQ":          {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"altrefaq:"}},
		"SetLayerAQMode":            {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"aq:"}},
		"SetLayerAutoAltRef":        {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"autoaltref:"}},
		"SetLayerBitrateKbps":       {kind: "vp9-spatial-svc-layer-control"},
		"SetLayerActiveMap":         {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"active:"}},
		"SetLayerARNR":              {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"arnrmax:", "arnrstrength:", "arnrtype:"}},
		"SetLayerColorRange":        {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"colorrange:"}},
		"SetLayerColorSpace":        {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"colorspace:"}},
		"SetLayerCPUUsed":           {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"cpu:"}},
		"SetLayerCQLevel":           {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"cq:"}},
		"SetLayerDeadline":          {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"deadline:"}},
		"SetLayerDeltaQUV":          {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"deltaquv:"}},
		"SetLayerDisableOvershootMaxQCBR": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"disovershoot:"},
		},
		"SetLayerDisableLoopfilter": {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"disableloopfilter:"}},
		"SetLayerEnableKeyFrameFiltering": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"--enable-keyframe-filtering"},
		},
		"SetLayerFrameDropAllowed": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"drop:"},
		},
		"SetLayerFrameParallelDecoding": {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"frame-parallel:"}},
		"SetLayerFrameParallelEncoderThreads": {
			kind: "vp9-spatial-svc-layer-control",
		},
		"SetLayerFramePeriodicBoost": {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"periodicboost:"}},
		"SetLayerKeyFrameInterval": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"kfmax:"},
		},
		"SetLayerKeyFrameIntervalRange": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"kfmin:", "kfmax:"},
		},
		"SetLayerGFCBRBoostPct":      {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"gfboost:"}},
		"SetLayerMaxGFInterval":      {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"maxgf:"}},
		"SetLayerMaxInterBitratePct": {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"maxinter:"}},
		"SetLayerMaxIntraBitratePct": {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"maxintra:"}},
		"SetLayerMinGFInterval":      {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"mingf:"}},
		"SetLayerLossless":           {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"lossless:"}},
		"SetLayerNextFrameQIndex":    {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"qonepass:"}},
		"SetLayerNoiseSensitivity": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"noise:"},
		},
		"SetLayerPostEncodeDrop": {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"postdrop:"}},
		"SetLayerRateControl":    {kind: "vp9-spatial-svc-layer-control"},
		"SetLayerRateControlBuffer": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"bufsz:", "bufinit:", "bufopt:"},
		},
		"SetLayerRenderSize":             {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"rendersize:"}},
		"SetLayerRTCExternalRateControl": {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"rtc:"}},
		"SetLayerRealtimeTarget": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"resize:", "bitrate:", "fps:", "minq:", "maxq:", "drop:"},
		},
		"SetLayerROIMap": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"roi:", "roicustom:"},
		},
		"SetLayerReferenceFrame": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"setref:"},
		},
		"SetLayerScreenContentMode": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"screen:"},
		},
		"SetLayerSharpness": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"sharpness:"},
		},
		"SetLayerStaticThreshold": {
			kind:         "vp9-spatial-svc-layer-control",
			helperTokens: []string{"static:"},
		},
		"SetLayerRowMT":           {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"rowmt:"}},
		"SetLayerTargetLevel":     {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"targetlevel:"}},
		"SetLayerEnableTPL":       {kind: "vp9-spatial-svc-layer-control"},
		"SetInterLayerPrediction": {kind: "libvpx-vp9-svc-control", helperTokens: []string{"inter-layer-pred:"}},
		"SetLayerTuning":          {kind: "vp9-spatial-svc-layer-control", helperTokens: []string{"tune:"}},
		"SetLayerTwoPassStats":    {kind: "vp9-spatial-svc-layer-control"},
		"SetTemporalLayerID":      {kind: "vp9-spatial-temporal-svc-control"},
		"SetTemporalScalability": {
			kind: "vp9-spatial-temporal-svc-control",
		},
	}
	assertPublicMethodMappings(t, "VP9SpatialSVCEncoder", methods, want)
}

func TestVP9SpatialSVCEncoderOptionsHaveParityMapping(t *testing.T) {
	fields := exportedFieldSet(t, VP9SpatialSVCEncoderOptions{})
	want := map[string]controlParityMapping{
		"InterLayerPrediction": {kind: "vp9-spatial-svc-layer-control"},
		"LayerCount":           {kind: "libvpx-vp9-svc-control"},
		"Layers":               {kind: "libvpx-vp9-svc-layer-config"},
	}
	assertOptionFieldMappings(t, "VP9SpatialSVCEncoderOptions", fields, want)
}
