//go:build ignore

// gen_mvref_blocks.go extracts the mv_ref_blocks[BLOCK_SIZES][8]
// POSITION table from libvpx v1.16.0 vp9/common/vp9_mvref_common.h
// and emits mvref_blocks.go. The table seeds the 8-neighbor search
// order for inter-block MV-ref candidate finding.
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
)

func findLibvpxSource(rel string) string {
	_, here, _, _ := runtime.Caller(0)
	dir := filepath.Dir(here)
	for _, root := range []string{"libvpx-v1.16.0-vp9", "libvpx-v1.16.0"} {
		d := dir
		for {
			path := filepath.Join(d, "internal", "coracle", "build", root, rel)
			if _, err := os.Stat(path); err == nil {
				return path
			}
			parent := filepath.Dir(d)
			if parent == d {
				break
			}
			d = parent
		}
	}
	return ""
}

func extractBraced(src, marker string) []int {
	idx := strings.Index(src, marker)
	if idx < 0 {
		return nil
	}
	open := strings.Index(src[idx:], "{")
	if open < 0 {
		return nil
	}
	open += idx
	depth := 0
	end := -1
	for i := open; i < len(src); i++ {
		switch src[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				end = i
			}
		}
		if end >= 0 {
			break
		}
	}
	if end < 0 {
		return nil
	}
	body := src[open+1 : end]
	body = regexp.MustCompile(`//[^\n]*`).ReplaceAllString(body, "")
	tokens := regexp.MustCompile(`-?\d+`).FindAllString(body, -1)
	out := make([]int, 0, len(tokens))
	for _, t := range tokens {
		v, err := strconv.Atoi(t)
		if err != nil {
			continue
		}
		out = append(out, v)
	}
	return out
}

func main() {
	src := findLibvpxSource("vp9/common/vp9_mvref_common.h")
	if src == "" {
		log.Fatal("libvpx source not found")
	}
	raw, err := os.ReadFile(src)
	if err != nil {
		log.Fatal(err)
	}
	text := string(raw)

	const rows = 13 // BLOCK_SIZES
	const cols = 8  // MVREF_NEIGHBOURS
	const expectedInts = rows * cols * 2

	vals := extractBraced(text, "mv_ref_blocks[BLOCK_SIZES][MVREF_NEIGHBOURS]")
	if len(vals) != expectedInts {
		log.Fatalf("mv_ref_blocks: got %d ints, want %d", len(vals), expectedInts)
	}

	out, err := os.Create("mvref_blocks.go")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()
	w := bufio.NewWriter(out)
	w.WriteString("// Code generated by gen_mvref_blocks.go from libvpx v1.16.0\n")
	w.WriteString("// vp9/common/vp9_mvref_common.h. DO NOT EDIT.\n\n")
	w.WriteString("package tables\n\n")
	w.WriteString("// Position mirrors libvpx's struct position — a signed (row,col)\n")
	w.WriteString("// pair used to address an 8x8 neighbor in the mode-info ring.\n")
	w.WriteString("type Position struct {\n\tRow, Col int8\n}\n\n")
	w.WriteString("// MvRefBlocks mirrors libvpx's mv_ref_blocks[BLOCK_SIZES][8] —\n")
	w.WriteString("// the eight-neighbor scan order the MV-ref candidate search uses\n")
	w.WriteString("// per block size to find inter predictors.\n")
	fmt.Fprintf(w, "var MvRefBlocks = [%d][%d]Position{\n", rows, cols)
	idx := 0
	for r := 0; r < rows; r++ {
		w.WriteString("\t{")
		for c := 0; c < cols; c++ {
			if c > 0 {
				w.WriteString(", ")
			}
			fmt.Fprintf(w, "{%d, %d}", vals[idx], vals[idx+1])
			idx += 2
		}
		w.WriteString("},\n")
	}
	w.WriteString("}\n")
	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}
	fmt.Fprintf(os.Stderr, "wrote mvref_blocks.go\n")
}
