//go:build ignore

// gen_scan.go reads libvpx v1.16.0 vp9/common/vp9_scan.c off disk and
// emits scan.go containing every scan-order, inverse-scan, and neighbor
// table verbatim. Run with `go run gen_scan.go` from this directory; the
// generated scan.go is committed alongside this generator so go test can
// validate parity even when libvpx isn't built.
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

func findLibvpxSource(rel string) string {
	_, here, _, _ := runtime.Caller(0)
	dir := filepath.Dir(here)
	for {
		path := filepath.Join(dir, "internal", "coracle", "build", "libvpx-v1.16.0", rel)
		if _, err := os.Stat(path); err == nil {
			return path
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// arrayPattern matches a DECLARE_ALIGNED static int16_t table with a 1D
// length. The length token may be a literal integer (e.g. 16) or an
// expression like "17 * MAX_NEIGHBORS"; the actual entry count is taken
// from the brace-body, not the declared length, so the expression form
// doesn't need to be evaluated.
var arrayPattern = regexp.MustCompile(
	`const\s+int16_t,\s+(\w+)\[[^\]]+\]\s*\)\s*=\s*{([^}]*)}`)

type table struct {
	name string
	rows int // number of values; for neighbor tables this is N*2.
	vals []int
}

func parseTables(src string) []table {
	matches := arrayPattern.FindAllStringSubmatch(src, -1)
	var tables []table
	for _, m := range matches {
		name := m[1]
		body := m[2]
		nums := regexp.MustCompile(`-?\d+`).FindAllString(body, -1)
		vals := make([]int, 0, len(nums))
		for _, n := range nums {
			v, err := strconv.Atoi(n)
			if err != nil {
				log.Fatalf("parse %q in %s: %v", n, name, err)
			}
			vals = append(vals, v)
		}
		tables = append(tables, table{name: name, rows: len(vals), vals: vals})
	}
	return tables
}

func goName(c string) string {
	// e.g. default_scan_4x4         -> DefaultScan4x4
	//      vp9_default_iscan_4x4    -> DefaultIScan4x4
	//      default_scan_4x4_neighbors -> DefaultScan4x4Neighbors
	c = strings.TrimPrefix(c, "vp9_")
	parts := strings.Split(c, "_")
	for i, p := range parts {
		switch p {
		case "iscan":
			parts[i] = "IScan"
			continue
		case "scan":
			parts[i] = "Scan"
			continue
		case "neighbors":
			parts[i] = "Neighbors"
			continue
		}
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

const fileHeader = `// Code generated by gen_scan.go from libvpx v1.16.0
// vp9/common/vp9_scan.c. DO NOT EDIT.

package tables
`

func emit(w *bufio.Writer, t table) {
	g := goName(t.name)
	fmt.Fprintf(w, "\n// %s mirrors libvpx %s.\nvar %s = [%d]int16{\n",
		g, t.name, g, t.rows)
	for i, v := range t.vals {
		if i%16 == 0 {
			w.WriteString("\t")
		}
		fmt.Fprintf(w, "%d,", v)
		if i%16 == 15 || i == len(t.vals)-1 {
			w.WriteString("\n")
		} else {
			w.WriteString(" ")
		}
	}
	w.WriteString("}\n")
}

func main() {
	src := findLibvpxSource("vp9/common/vp9_scan.c")
	if src == "" {
		log.Fatal("libvpx source not found; run `make oracle-tools` first")
	}
	raw, err := os.ReadFile(src)
	if err != nil {
		log.Fatal(err)
	}
	tables := parseTables(string(raw))
	if len(tables) == 0 {
		log.Fatal("no tables matched; arrayPattern likely needs updating")
	}
	sort.SliceStable(tables, func(i, j int) bool { return tables[i].name < tables[j].name })

	out, err := os.Create("scan.go")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()
	w := bufio.NewWriter(out)
	w.WriteString(fileHeader)
	for _, t := range tables {
		emit(w, t)
	}
	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d tables to scan.go\n", len(tables))
}
