//go:build ignore

// gen_coef_probs.go reads libvpx v1.16.0 vp9/common/vp9_entropy.c
// and emits coef_probs.go with the four default_coef_probs_{4,8,16,32}x{...}
// tables in fixed [PLANE_TYPES][REF_TYPES][COEF_BANDS][COEFF_CONTEXTS]
// [UNCONSTRAINED_NODES] storage shape. The C initializer leaves
// band-0 with only 3 context rows (vs 6 for bands 1..5); the unused
// slots are zero-filled to match libvpx's struct layout.
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
)

func findLibvpxSource(rel string) string {
	_, here, _, _ := runtime.Caller(0)
	dir := filepath.Dir(here)
	for {
		path := filepath.Join(dir, "internal", "coracle", "build", "libvpx-v1.16.0", rel)
		if _, err := os.Stat(path); err == nil {
			return path
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

const (
	planeTypes         = 2
	refTypes           = 2
	coefBands          = 6
	coefContexts       = 6
	unconstrainedNodes = 3
	band0Contexts      = 3
)

func extractBraced(src, name string) []int {
	needle := name + "["
	idx := strings.Index(src, needle)
	if idx < 0 {
		return nil
	}
	open := strings.Index(src[idx:], "{")
	if open < 0 {
		return nil
	}
	open += idx
	depth := 0
	end := -1
	for i := open; i < len(src); i++ {
		switch src[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				end = i
			}
		}
		if end >= 0 {
			break
		}
	}
	if end < 0 {
		return nil
	}
	body := src[open+1 : end]
	body = regexp.MustCompile(`//[^\n]*`).ReplaceAllString(body, "")
	tokens := regexp.MustCompile(`-?\d+`).FindAllString(body, -1)
	out := make([]int, 0, len(tokens))
	for _, t := range tokens {
		v, err := strconv.Atoi(t)
		if err != nil {
			continue
		}
		out = append(out, v)
	}
	return out
}

// expandPerPlaneRef takes the 99-value sparse init for a single
// (plane, ref) — 3 context rows for band 0 + 5*6 for bands 1..5 —
// and returns the 108-value rectangular form expected by storage.
func expandPerPlaneRef(in []int) []int {
	out := make([]int, 0, 108)
	// Band 0: 3 real rows + 3 zero rows.
	out = append(out, in[:band0Contexts*unconstrainedNodes]...)
	for i := 0; i < (coefContexts-band0Contexts)*unconstrainedNodes; i++ {
		out = append(out, 0)
	}
	// Bands 1..5: copy through.
	out = append(out, in[band0Contexts*unconstrainedNodes:]...)
	return out
}

func main() {
	src := findLibvpxSource("vp9/common/vp9_entropy.c")
	if src == "" {
		log.Fatal("libvpx source not found")
	}
	raw, err := os.ReadFile(src)
	if err != nil {
		log.Fatal(err)
	}
	text := string(raw)

	tables := []struct {
		name   string
		goName string
	}{
		{"default_coef_probs_4x4", "DefaultCoefProbs4x4"},
		{"default_coef_probs_8x8", "DefaultCoefProbs8x8"},
		{"default_coef_probs_16x16", "DefaultCoefProbs16x16"},
		{"default_coef_probs_32x32", "DefaultCoefProbs32x32"},
	}

	const valuesPerTable = 1584
	const valuesPerPlaneRef = 99

	out, err := os.Create("coef_probs.go")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()
	w := bufio.NewWriter(out)
	w.WriteString("// Code generated by gen_coef_probs.go from libvpx v1.16.0\n")
	w.WriteString("// vp9/common/vp9_entropy.c. DO NOT EDIT.\n\n")
	w.WriteString("package tables\n\n")
	w.WriteString("// Default coefficient probabilities seed FrameContext.CoefProbs.\n")
	w.WriteString("// Layout per table:\n")
	w.WriteString("//   [PLANE_TYPES=2][REF_TYPES=2][COEF_BANDS=6][COEFF_CONTEXTS=6][UNCONSTRAINED_NODES=3]\n")
	w.WriteString("// Band 0 only uses contexts 0..2; the remaining three slots are\n")
	w.WriteString("// zero-padded to match libvpx's rectangular vp9_coeff_probs_model\n")
	w.WriteString("// storage shape.\n\n")

	for _, t := range tables {
		vals := extractBraced(text, t.name)
		if vals == nil {
			log.Fatalf("%s: not found", t.name)
		}
		// Sparse init: 2 * 2 * (3 + 5*6) * 3 = 396 per tx_size.
		expectedSparse := planeTypes * refTypes * (band0Contexts + (coefBands-1)*coefContexts) * unconstrainedNodes
		if len(vals) != expectedSparse {
			log.Fatalf("%s: got %d values, want %d", t.name, len(vals), expectedSparse)
		}

		// Expand to rectangular layout — 432 values per tx_size.
		expanded := make([]int, 0, valuesPerTable/4*planeTypes*refTypes)
		for pr := 0; pr < planeTypes*refTypes; pr++ {
			start := pr * valuesPerPlaneRef
			expanded = append(expanded, expandPerPlaneRef(vals[start:start+valuesPerPlaneRef])...)
		}

		fmt.Fprintf(w, "// %s mirrors libvpx's %s with band-0 zero padding.\n", t.goName, t.name)
		fmt.Fprintf(w, "var %s = [%d][%d][%d][%d][%d]uint8{\n",
			t.goName, planeTypes, refTypes, coefBands, coefContexts, unconstrainedNodes)
		idx := 0
		for p := 0; p < planeTypes; p++ {
			fmt.Fprintf(w, "\t{\n")
			for r := 0; r < refTypes; r++ {
				fmt.Fprintf(w, "\t\t{\n")
				for b := 0; b < coefBands; b++ {
					fmt.Fprintf(w, "\t\t\t{\n")
					for c := 0; c < coefContexts; c++ {
						fmt.Fprintf(w, "\t\t\t\t{")
						for n := 0; n < unconstrainedNodes; n++ {
							if n > 0 {
								w.WriteString(", ")
							}
							fmt.Fprintf(w, "%d", expanded[idx])
							idx++
						}
						w.WriteString("},\n")
					}
					fmt.Fprintf(w, "\t\t\t},\n")
				}
				fmt.Fprintf(w, "\t\t},\n")
			}
			fmt.Fprintf(w, "\t},\n")
		}
		fmt.Fprintf(w, "}\n\n")
	}
	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}
	fmt.Fprintf(os.Stderr, "wrote coef_probs.go with %d tables\n", len(tables))
}
