//go:build ignore

// gen_detok_tables.go reads libvpx v1.16.0 vp9/common/vp9_entropy.c and
// emits detok_tables.go with the detokenize-time probability blobs:
//   - vp9_cat{1..6}_prob (8-bit profile)
//   - vp9_pareto8_full (255 rows × 8 nodes)
//   - vp9_coefband_trans_4x4 (16 bytes)
//   - vp9_coefband_trans_8x8plus (1024 bytes)
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
)

func findLibvpxSource(rel string) string {
	_, here, _, _ := runtime.Caller(0)
	dir := filepath.Dir(here)
	for {
		path := filepath.Join(dir, "internal", "coracle", "build", "libvpx-v1.16.0-vp9", rel)
		if _, err := os.Stat(path); err == nil {
			return path
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// extractBraced reads the brace-delimited initializer that follows the
// first occurrence of `marker` (typically `vp9_xxx[`), walking brace
// depth so nested initializers are handled. Line comments are stripped
// before tokenizing so digits inside `// foo 16x16` don't leak in.
func extractBraced(src, marker string) []int {
	idx := strings.Index(src, marker)
	if idx < 0 {
		return nil
	}
	open := strings.Index(src[idx:], "{")
	if open < 0 {
		return nil
	}
	open += idx
	depth := 0
	end := -1
	for i := open; i < len(src); i++ {
		switch src[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				end = i
			}
		}
		if end >= 0 {
			break
		}
	}
	if end < 0 {
		return nil
	}
	body := src[open+1 : end]
	body = regexp.MustCompile(`//[^\n]*`).ReplaceAllString(body, "")
	tokens := regexp.MustCompile(`-?\d+`).FindAllString(body, -1)
	out := make([]int, 0, len(tokens))
	for _, t := range tokens {
		v, err := strconv.Atoi(t)
		if err != nil {
			continue
		}
		out = append(out, v)
	}
	return out
}

func main() {
	src := findLibvpxSource("vp9/common/vp9_entropy.c")
	if src == "" {
		log.Fatal("libvpx source not found")
	}
	raw, err := os.ReadFile(src)
	if err != nil {
		log.Fatal(err)
	}
	text := string(raw)

	out, err := os.Create("detok_tables.go")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()
	w := bufio.NewWriter(out)
	w.WriteString("// Code generated by gen_detok_tables.go from libvpx v1.16.0\n")
	w.WriteString("// vp9/common/vp9_entropy.c. DO NOT EDIT.\n\n")
	w.WriteString("package tables\n\n")
	w.WriteString("// VP9 token-tail probability blobs used during detokenize.\n")
	w.WriteString("// Mirrors vp9_cat{1..6}_prob, vp9_pareto8_full, and the\n")
	w.WriteString("// vp9_coefband_trans_{4x4,8x8plus} band-translate maps.\n\n")

	flat := func(name, gName string, n int) {
		v := extractBraced(text, name+"[")
		if len(v) != n {
			log.Fatalf("%s: got %d, want %d", name, len(v), n)
		}
		fmt.Fprintf(w, "// %s mirrors libvpx's %s.\n", gName, name)
		fmt.Fprintf(w, "var %s = [%d]uint8{", gName, n)
		for i, x := range v {
			if i > 0 {
				w.WriteString(", ")
			}
			fmt.Fprintf(w, "%d", x)
		}
		w.WriteString("}\n\n")
	}

	flat("vp9_cat1_prob", "Cat1Prob", 1)
	flat("vp9_cat2_prob", "Cat2Prob", 2)
	flat("vp9_cat3_prob", "Cat3Prob", 3)
	flat("vp9_cat4_prob", "Cat4Prob", 4)
	flat("vp9_cat5_prob", "Cat5Prob", 5)
	flat("vp9_cat6_prob", "Cat6Prob", 14)
	flat("vp9_coefband_trans_4x4", "CoefbandTrans4x4", 16)
	flat("vp9_coefband_trans_8x8plus", "CoefbandTrans8x8Plus", 1024)

	// vp9_pareto8_full: 255 rows × 8 nodes.
	const rows, cols = 255, 8
	pv := extractBraced(text, "vp9_pareto8_full[")
	if len(pv) != rows*cols {
		log.Fatalf("vp9_pareto8_full: got %d, want %d", len(pv), rows*cols)
	}
	fmt.Fprintf(w, "// Pareto8Full mirrors libvpx's vp9_pareto8_full[255][8].\n")
	fmt.Fprintf(w, "var Pareto8Full = [%d][%d]uint8{\n", rows, cols)
	idx := 0
	for r := 0; r < rows; r++ {
		w.WriteString("\t{")
		for c := 0; c < cols; c++ {
			if c > 0 {
				w.WriteString(", ")
			}
			fmt.Fprintf(w, "%d", pv[idx])
			idx++
		}
		w.WriteString("},\n")
	}
	w.WriteString("}\n")
	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}
	fmt.Fprintf(os.Stderr, "wrote detok_tables.go\n")
}
