//go:build ignore

// gen_kf_probs.go reads libvpx v1.16.0 vp9/common/vp9_entropymode.c
// and emits kf_probs.go with the (vp9_kf_y_mode_prob,
// vp9_kf_uv_mode_prob, vp9_kf_partition_probs) tables. The 10x10x9
// kf_y_mode_prob is 900 bytes — too big to type reliably, so we
// generate it once and commit the output alongside this generator.
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
)

func findLibvpxSource(rel string) string {
	_, here, _, _ := runtime.Caller(0)
	dir := filepath.Dir(here)
	for {
		path := filepath.Join(dir, "internal", "coracle", "build", "libvpx-v1.16.0", rel)
		if _, err := os.Stat(path); err == nil {
			return path
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

func extractBraced(src, name string) []int {
	needle := name + "["
	idx := strings.Index(src, needle)
	if idx < 0 {
		return nil
	}
	open := strings.Index(src[idx:], "{")
	if open < 0 {
		return nil
	}
	open += idx
	depth := 0
	end := -1
	for i := open; i < len(src); i++ {
		switch src[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				end = i
			}
		}
		if end >= 0 {
			break
		}
	}
	if end < 0 {
		return nil
	}
	body := src[open+1 : end]
	// Strip line comments first so any digits inside them (rare but
	// possible) don't pollute the value list.
	body = regexp.MustCompile(`//[^\n]*`).ReplaceAllString(body, "")
	tokens := regexp.MustCompile(`-?\d+`).FindAllString(body, -1)
	out := make([]int, 0, len(tokens))
	for _, t := range tokens {
		v, err := strconv.Atoi(t)
		if err != nil {
			continue
		}
		out = append(out, v)
	}
	return out
}

func main() {
	src := findLibvpxSource("vp9/common/vp9_entropymode.c")
	if src == "" {
		log.Fatal("libvpx source not found; run `make oracle-tools` or build_libvpx_vp9.sh first")
	}
	raw, err := os.ReadFile(src)
	if err != nil {
		log.Fatal(err)
	}
	text := string(raw)

	tables := []struct {
		name   string
		dim    []int // dim layout for the emitted Go var
		goName string
	}{
		{"vp9_kf_y_mode_prob", []int{10, 10, 9}, "KfYModeProb"},
		{"vp9_kf_uv_mode_prob", []int{10, 9}, "KfUvModeProb"},
		{"vp9_kf_partition_probs", []int{16, 3}, "KfPartitionProbs"},
	}

	out, err := os.Create("kf_probs.go")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()
	w := bufio.NewWriter(out)
	w.WriteString("// Code generated by gen_kf_probs.go from libvpx v1.16.0\n")
	w.WriteString("// vp9/common/vp9_entropymode.c. DO NOT EDIT.\n\n")
	w.WriteString("package tables\n\n")

	for _, t := range tables {
		vals := extractBraced(text, t.name)
		if vals == nil {
			log.Fatalf("%s: not found in source", t.name)
		}
		expected := 1
		for _, d := range t.dim {
			expected *= d
		}
		if len(vals) != expected {
			// Debug: print last 30 values and any extras to help diagnose.
			log.Printf("%s: got %d values, want %d (dim %v); first 9 = %v; last 30 = %v",
				t.name, len(vals), expected, t.dim, vals[:9], vals[len(vals)-30:])
			os.Exit(1)
		}

		// Emit the Go declaration.
		dimStr := ""
		for _, d := range t.dim {
			dimStr += fmt.Sprintf("[%d]", d)
		}
		fmt.Fprintf(w, "// %s mirrors libvpx's %s.\n", t.goName, t.name)
		fmt.Fprintf(w, "var %s = %suint8{\n", t.goName, dimStr)
		emitNested(w, vals, t.dim, 0, "\t")
		fmt.Fprintf(w, "}\n\n")
	}
	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}
	fmt.Fprintf(os.Stderr, "wrote kf_probs.go with %d tables\n", len(tables))
}

// emitNested writes the dim[level] entries at the current level —
// caller owns the surrounding `{` and `}` of THIS level. For dim
// [10, 10, 9], the outermost caller writes `var X = [10][10][9]uint8{`
// then `emitNested(level=0)` then `}`. At level=0 we emit 10 entries
// each wrapped in `{` (recursive) `}`. At level=len(dim)-1 we emit
// dim[level] integers separated by commas (no surrounding braces).
func emitNested(w *bufio.Writer, vals []int, dim []int, level int, indent string) {
	if level == len(dim)-1 {
		for i := 0; i < dim[level]; i++ {
			if i > 0 {
				w.WriteString(", ")
			}
			fmt.Fprintf(w, "%d", vals[i])
		}
		return
	}
	stride := 1
	for _, d := range dim[level+1:] {
		stride *= d
	}
	for i := 0; i < dim[level]; i++ {
		if level == len(dim)-2 {
			// Next level is leaf — write the row inline.
			fmt.Fprintf(w, "%s{", indent)
			emitNested(w, vals[i*stride:], dim, level+1, indent+"\t")
			w.WriteString("},\n")
		} else {
			fmt.Fprintf(w, "%s{\n", indent)
			emitNested(w, vals[i*stride:], dim, level+1, indent+"\t")
			fmt.Fprintf(w, "%s},\n", indent)
		}
	}
}
